version: '3'

networks:
  rs_ananda:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local

services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ./app:/var/www:cached
      - ${HOST_SSH_PATH}:/root/.ssh
    extra_hosts:
      - "dockerhost:10.0.75.1"
    ports:
      - "2222:22"
    tty: true
    networks:
      - rs_ananda
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./docker/php-fpm/php7.2.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www:cached
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:10.0.75.1"
    environment:
      - FAKETIME=0
    depends_on:
      - workspace
    networks:
      - rs_ananda
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ./app:/var/www:cached
      - ./docker/logs/nginx/:/var/log/nginx
      - ./docker/nginx/sites/:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      rs_ananda:
        aliases:
          - user-sso.rsananda.local
          - accounting.rsananda.local
          - inventory.rsananda.local
  mysql:
    build:
      context: ./docker/mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - rs_ananda
  redis:
    build: ./docker/redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "6379:6379"
    networks:
      - rs_ananda
  php-worker:
    build:
      context: ./docker/php-worker
    volumes:
      - ./app:/var/www:cached
      - ./docker/php-worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:10.0.75.1"
    networks:
      - rs_ananda
  # node:
  #   image: node:${NODE_VERSION}
  #   ports:
  #     - 8080:8080
  #   command: bash -c "npm install && npm run watch"
  #   working_dir: /var/www/pos
  #   volumes:
  #     - ./app:/var/www:cached
  #   environment:
  #     HOST: 0.0.0.0
  #   depends_on:
  #     - workspace
  #   networks:
  #     - rs_ananda